name: gis_tools
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - xarray
  - zarr
  - numcodecs
  - rioxarray
  - rasterio
  - numpy
  - dask
  - tqdm
  - geopandas
  - pyproj
  - shapely
  - fiona
  - pandas
  - pyarrow
  - pytest
  - h5py
  - requests
  - arosics>=1.3.0
  - gdal
  - openjpeg
  - libgdal-jp2openjpeg
  - scipy
  - pillow
  - opencv
  - pip
  - opencv
